name: "Node CI"
on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron: "0 4 * * *"

strategy:
  matrix:
    node-version: ['18.x', '20.x']

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
